/**
 * 技能单一源 → 双 runtime 投影生成器。
 *
 * 权威源：`skills/rudder-<name>.md`（唯一手写处）
 * 投影一：`.claude/commands/rudder-<name>.md`
 * 投影二：`.hermes/skills/rudder-<name>/SKILL.md`
 *
 * 渲染规则（详见 openspec/changes/v6-requirement-lifecycle/specs/skill-single-source）：
 * - frontmatter 两段展开：`claude:` 段 → Claude 投影，`hermes:` 段 → Hermes 投影。
 * - 标题按 runtime 区分：`# Command: rudder-<name>` / `# Skill: rudder-<name>`。
 * - `<!-- hermes-only:start -->` / `<!-- hermes-only:end -->` 包裹的区块只进 Hermes 投影。
 * - 两个投影顶部均写入 GENERATED 标识。
 *
 * 用法：
 *   node scripts/sync-skills.js          # 写入全部投影
 *   node scripts/sync-skills.js --check  # 逐字节比对，不一致则列出文件并退出码 1
 */

import { readFileSync, writeFileSync, existsSync, readdirSync, mkdirSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const SKILLS_DIR = join(ROOT, 'skills');
const CLAUDE_DIR = join(ROOT, '.claude', 'commands');
const HERMES_DIR = join(ROOT, '.hermes', 'skills');

const HERMES_BLOCK = /[ \t]*<!-- hermes-only:start -->[\s\S]*?<!-- hermes-only:end -->[ \t]*\n?/g;
const HERMES_MARKERS = /^[ \t]*<!-- hermes-only:(?:start|end) -->[ \t]*\n?/gm;

/**
 * 解析权威源：两段式 frontmatter + 正文。
 * 只支持本仓库用到的 YAML 子集（嵌套映射一层 + 字符串列表），不引入第三方依赖。
 */
function parseSource(text, file) {
  const m = text.match(/^---\n([\s\S]*?)\n---\n?/);
  if (!m) throw new Error(`${file}: 缺少 frontmatter`);

  const data = {};
  let section = null;
  let listKey = null;

  for (const raw of m[1].split('\n')) {
    const line = raw.trim();
    if (line === '' || line.startsWith('#')) continue;
    const indented = /^\s/.test(raw);

    if (!indented) {
      const kv = line.match(/^([A-Za-z_-]+):\s*(.*)$/);
      if (!kv) throw new Error(`${file}: 无法解析 frontmatter 行「${line}」`);
      if (kv[2] === '') {
        section = kv[1];
        data[section] = {};
        listKey = null;
      } else {
        section = null;
        data[kv[1]] = kv[2];
      }
      continue;
    }

    if (section === null) throw new Error(`${file}: frontmatter 缩进行「${line}」无所属段落`);
    if (line.startsWith('- ')) {
      if (!listKey) throw new Error(`${file}: 列表项「${line}」没有所属键`);
      data[section][listKey].push(line.slice(2).trim());
      continue;
    }
    const kv = line.match(/^([A-Za-z_-]+):\s*(.*)$/);
    if (!kv) throw new Error(`${file}: 无法解析 frontmatter 行「${line}」`);
    if (kv[2] === '') {
      listKey = kv[1];
      data[section][listKey] = [];
    } else {
      data[section][kv[1]] = kv[2];
      listKey = null;
    }
  }

  return { data, body: text.slice(m[0].length) };
}

/** 校验两段 frontmatter 的必备字段；返回缺失描述数组（空数组表示通过）。 */
function validate(name, data) {
  const missing = [];
  const claude = data.claude ?? {};
  const hermes = data.hermes ?? {};
  if (!claude['argument-hint']) missing.push(`claude.argument-hint（Claude Code 专属字段）`);
  if (!claude.description) missing.push('claude.description');
  if (!hermes.name) missing.push('hermes.name');
  if (!hermes.description) missing.push('hermes.description');
  if (!Array.isArray(hermes.triggers) || hermes.triggers.length === 0) {
    missing.push(`hermes.triggers（Hermes 专属字段）`);
  }
  return missing;
}

/** 归一化正文：折叠多余空行并去除首尾空白，保证渲染确定。 */
function normalize(text) {
  return text.replace(/\n{3,}/g, '\n\n').trim();
}

function renderClaude(name, data, body) {
  const claude = data.claude;
  const shared = normalize(body.replace(HERMES_BLOCK, ''));
  return `---
description: ${claude.description}
argument-hint: ${claude['argument-hint']}
---

<!-- GENERATED by scripts/sync-skills.js from skills/rudder-${name}.md — DO NOT EDIT -->

# Command: rudder-${name}

${shared}
`;
}

function renderHermes(name, data, body) {
  const hermes = data.hermes;
  const triggers = hermes.triggers.map((t) => `  - ${t}`).join('\n');
  const full = normalize(body.replace(HERMES_MARKERS, ''));
  return `---
name: ${hermes.name}
description: ${hermes.description}
triggers:
${triggers}
---

<!-- GENERATED by scripts/sync-skills.js from skills/rudder-${name}.md — DO NOT EDIT -->

# Skill: rudder-${name}

${full}
`;
}

/** 列出权威源的技能名（去掉 `rudder-` 前缀与扩展名；排序保证输出顺序确定）。 */
function listSources() {
  if (!existsSync(SKILLS_DIR)) return [];
  return readdirSync(SKILLS_DIR)
    .filter((f) => /^rudder-.+\.md$/.test(f))
    .map((f) => f.replace(/^rudder-/, '').replace(/\.md$/, ''))
    .sort();
}

/** 渲染全部投影，返回 { name, targets: [{ path, content }] } 列表。 */
function renderAll() {
  const out = [];
  const errors = [];
  for (const name of listSources()) {
    const file = join(SKILLS_DIR, `rudder-${name}.md`);
    let parsed;
    try {
      parsed = parseSource(readFileSync(file, 'utf8'), relative(ROOT, file));
    } catch (err) {
      errors.push(err.message);
      continue;
    }
    const missing = validate(name, parsed.data);
    if (missing.length > 0) {
      errors.push(`${relative(ROOT, file)}: frontmatter 字段缺失 → ${missing.join('、')}`);
      continue;
    }
    out.push({
      name,
      targets: [
        {
          path: join(CLAUDE_DIR, `rudder-${name}.md`),
          content: renderClaude(name, parsed.data, parsed.body),
        },
        {
          path: join(HERMES_DIR, `rudder-${name}`, 'SKILL.md'),
          content: renderHermes(name, parsed.data, parsed.body),
        },
      ],
    });
  }
  return { rendered: out, errors };
}

/**
 * 找出磁盘上存在、但已无权威源对应的投影（技能改名/删除后的残留）。
 * 期望集合直接取自渲染结果，避免路径规则在两处各写一遍而漂移。
 */
function findOrphans(rendered) {
  const expected = new Set(rendered.flatMap((r) => r.targets.map((t) => t.path)));
  const orphans = [];
  if (existsSync(CLAUDE_DIR)) {
    for (const f of readdirSync(CLAUDE_DIR)) {
      const full = join(CLAUDE_DIR, f);
      if (/^rudder-.*\.md$/.test(f) && !expected.has(full)) orphans.push(full);
    }
  }
  if (existsSync(HERMES_DIR)) {
    for (const d of readdirSync(HERMES_DIR)) {
      const full = join(HERMES_DIR, d, 'SKILL.md');
      if (/^rudder-/.test(d) && existsSync(full) && !expected.has(full)) orphans.push(full);
    }
  }
  return orphans;
}

function main() {
  const checkMode = process.argv.includes('--check');
  const { rendered, errors } = renderAll();

  if (errors.length > 0) {
    console.error('❌ 权威源校验失败：');
    for (const e of errors) console.error(`   - ${e}`);
    process.exitCode = 1;
    return;
  }

  const orphans = findOrphans(rendered);

  if (checkMode) {
    const drifted = [];
    for (const { targets } of rendered) {
      for (const { path, content } of targets) {
        const rel = relative(ROOT, path);
        if (!existsSync(path)) drifted.push(`${rel}（缺失，未生成）`);
        else if (readFileSync(path, 'utf8') !== content) drifted.push(`${rel}（内容漂移）`);
      }
    }
    for (const o of orphans) drifted.push(`${relative(ROOT, o)}（无对应权威源，应删除）`);

    if (drifted.length === 0) {
      console.log(`✅ 技能投影与权威源一致（共 ${rendered.length} 个技能 × 2 个投影）`);
      process.exitCode = 0;
      return;
    }
    console.error('❌ 技能投影与权威源不一致：');
    for (const d of drifted) console.error(`   - ${d}`);
    console.error('   修复：运行 node scripts/sync-skills.js');
    process.exitCode = 1;
    return;
  }

  let written = 0;
  for (const { targets } of rendered) {
    for (const { path, content } of targets) {
      mkdirSync(join(path, '..'), { recursive: true });
      writeFileSync(path, content, 'utf8');
      written += 1;
    }
  }
  console.log(`✅ 已生成 ${written} 个技能投影（${rendered.length} 个技能 × 2 个 runtime）`);
  if (orphans.length > 0) {
    console.warn('⚠️ 以下投影已无对应权威源，请手工删除：');
    for (const o of orphans) console.warn(`   - ${relative(ROOT, o)}`);
  }
}

main();
